LETTERS = 'ABCDEFGHJKLMNOPQRS'
TICKER = 'GAZP'
DAY_NUMBER = 5

FINAL_FILE_DIRECTORY = r'D:\\mps\\'
SOURCE_TXT_DIRECTORY = r'D:\\mps\\'

MAIN_DIRECTORY = "C:/mp"
MP_IMAGES_DIRECTORY = "C:/mp/mp_images"
